# Description: Docker Compose file to run cheqd-mcp-server
# SYNTAX: docker compose -f docker/docker-compose.yml up --detach

services:
  # ACA-Py Holder Agent
  acapy-holder:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    container_name: holder
    ports:
      - "4001:4001"
      - "4002:4002"
    restart: on-failure
    command: >
      start
        --label Holder
        --inbound-transport http 0.0.0.0 4002
        --outbound-transport http
        --endpoint http://holder:4002
        --admin 0.0.0.0 4001
        --admin-insecure-mode
        --wallet-type askar-anoncreds
        --wallet-name holder
        --wallet-key insecure
        --auto-provision
        --auto-accept-invites
        --auto-accept-requests
        --auto-ping-connection
        --log-level info
        --no-ledger
        --plugin cheqd
        --plugin-config plugin-config.yml
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:4001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network
networks:
  mcp-network:
    external: true
