FROM ghcr.io/openwallet-foundation/acapy-agent:py3.12-1.2.4

USER root

# install plugins as binaries
RUN pip install git+https://github.com/openwallet-foundation/acapy-plugins@main#subdirectory=cheqd

COPY ./plugin-config.yml ./

ENTRYPOINT ["aca-py"]
