FROM ghcr.io/openwallet-foundation/acapy-agent:py3.13-1.5.0rc0

USER root

# install plugins as binaries
RUN pip install git+https://github.com/openwallet-foundation/acapy-plugins@main#subdirectory=cheqd

COPY ./plugin-config.yml ./

ENTRYPOINT ["aca-py"]
