# Description: Docker Compose file to run cheqd-mcp-server
# SYNTAX: docker compose -f docker/docker-compose.yml up --detach

services:
  mcp-server:
    # OPTIONAL: Rebuild cheqd mcp-toolkit Docker image, if you want build your own
    # Default is to pull in the pre-published image on GitHub Container Registry
    # SYNTAX: docker compose -f docker/docker-compose.yml build
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    image: ghcr.io/cheqd/mcp-toolkit:latest
    container_name: faber
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ../env.example
    networks:
      - mcp-network
networks:
  mcp-network:
    name: mcp-network
    driver: bridge
