name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash
env:
  CI: true

jobs:
  run-build:
    name: "Build packages"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Clean install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Run pnpm build"
        run: pnpm build